public class Main {
    public static void main(String[] args) {
        System.out.println("Baris 1\nBaris 2");         // \n
        System.out.println("Nama\t: Sri");              // \t
        System.out.println("Path\t: C:\\Users\\Sri");   // \\
        System.out.println("Kata : \"Java\"");          // \"
        System.out.println("Char : \'A\'");             // \'
        System.out.println("Helloo\b");                 // \b
        System.out.println("Hello\rHi!");               // \r

        
        // \n Newline (baris baru)
        // \t Tab (spasi panjang setara tabulasi)
        // \\ Menampilkan karakter backslash 
        // \" Menampilkan tanda kutip ganda
        // \n Menampilkan tanda kutip tunggal
        // \b Backspace (menghapus 1 karakter sebelumnya)
        /* \r carriage return (mengembalikan kursor ke awal baris,
              sering dipakai di sistem lama/Windows)*/
        // \f form feed (jarang dipakai, biasanya untuk printer lama).
     
    }  
}
